### ISSUE TITLE
Dicentrics analisys

### ISSUE THREAD

**Issue by neliner** [biodosetools-team/biodosetools#26]
[Dicentrics analisys.docx](https://github.com/biodosetools-team/biodosetools/files/6170173/Dicentrics.analisys.docx)

Biodose tool 
- Version: 3.4.0
- Module: Dicentrics analisys
-I can not calculate dose irradiation using Dicentrics analisys. An error has occurred.

**Comment by aldomann** [comment]
Thank you for reporting the issue.

There is an issue  with Merkle's method for the whole-body assessment (the calculation is successful if you use Delta method):
```r
Warning: Error in stats::uniroot: f() values at end points not of opposite sign
```

I will review the code and fix it as soon as possible.
